---
- hosts: lab_aws_servers
  become: true
  vars:
    new_user: labadmin

  tasks:
    - name: Setup passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Create the new user named {{ new_user }} with sudo privileges
      user:
        name: "{{ new_user }}"
        state: present
        groups: sudo
        shell: /bin/bash
        append: true
        create_home: true
